import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import '../styles/globals.css'
import { useEffect, useRef } from 'react';
import useTheme from './../hooks/useTheme';
import CustomCursor from '../components/CustomCursor';

function MyApp({ Component, pageProps }) {
    const [detectTheme] = useTheme();
    // const cursor = useRef();

    useEffect(() => {
        detectTheme();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    return (
        <>
            <Head>
                <title>Yash Dand | Full Stack Developer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/favicon.png" />
            </Head>
            <div className='min-h-screen flex flex-col'>
                <Header />
                <main className='flex-grow'>
                    <Component {...pageProps} />
                </main>
                <Footer />
                <CustomCursor />
            </div>
        </>
    )
}

export default MyApp
